name: Build ES Docker

on:
  push:

jobs:
  build-es-docker:
    name: Build ES Docker
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
       

    - name: Install Required Packages
      run: sudo pip3 install jinja2-cli && release-tools/scripts/required_packages.sh

    - name: Log into registry
      run: echo "${{ secrets.dockerhub_token }}" | docker login -u splitice --password-stdin

    - name: Starting ES Docker Build
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        echo "Executing On-demand Build for ES Docker Image"
        ODFE_VER=`./release-tools/scripts/version-info.sh --od`
        echo "ODFE VERSION $ODFE_VER"
        workdir=`pwd`
        ./release-tools/scripts/docker_download_plugins.sh elasticsearch
        cd elasticsearch/docker
        make build
        
        docker images|grep "amazon/opendistro-for-elasticsearch" > docker_id.out
        image_id=`awk -F ' ' '{print $3}' docker_id.out`
        DOCKER_NAME=odfe-test-$ODFE_VER
        echo "Docker Id is $image_id"
        docker tag $image_id halleyassistau/opendistroforelasticsearch:$ODFE_VER
        docker tag $image_id halleyassistau/opendistroforelasticsearch:latest
        docker images
        docker push halleyassistau/opendistroforelasticsearch:$ODFE_VER
        docker push halleyassistau/opendistroforelasticsearch:latest
        docker logout
        cd ../../..
        ls -ltr